name: license_plate_rwanda
description: Validate a Rwandan car/motorcycle plate number of Diplomatic, Foreigners, National Police, Military Force, Government Projects, and Normal citizens
version: 0.0.2
homepage: https://github.com/knowbee/license_plate_rwanda

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
